# Don't edit this file
#
# It was auto generated by CMake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES napscene napparameter napartnet napmidi napsequence)
set(DEEP_DEPENDENT_NAP_MODULES napscene napparameter napartnet napmidi napsequence napmath napcolor napasio napsdlinput napinput napapp)
set(DEEP_DEPENDENT_RPATHS ../../../../system_modules/napartnet/thirdparty/libartnet/msvc/x86_64/bin/Release ../../../../system_modules/naprender/thirdparty/sdl/msvc/x86_64/lib)
